@baseUrl = http://localhost:3000
@accessToken = Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UxNjJiMzA0ZjZjNDg1YzYxMThjNWMiLCJpYXQiOjE3NDI4MjYwNjQsImV4cCI6MTc0MjgzMzI2NH0.C2PlG-zRdFD6Ybe_jsuiA0dk8fbTuptFiTTm6LGStco
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UxNjJiMzA0ZjZjNDg1YzYxMThjNWMiLCJpYXQiOjE3NDI4MjQ2NzgsImV4cCI6MTc0MzQyOTQ3OH0.uSNjOklq3Rkg3mP12GfAP07tkvrH6pcFTTgI7HYT4_E

@nikname = pepito123

### Registro de usuario con rol de user
POST {{baseUrl}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "nickname": "pepito123",
  "email": "panzerpro25@gmail.com",
  "password": "1234567890"
}

### Validacion del email
PUT {{baseUrl}}/api/auth/validate HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  "verificationCode": "748000"
}

### Login
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "panzerpro25@gmail.com",
  "password": "1234567890"
}

### Completar registro de usuario con foto de perfil
PUT {{baseUrl}}/api/users/complete-register HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: {{accessToken}}

--Boundry
Content-Disposition: form-data; name="name"
Content-Type: text/plain

Raúl
--Boundry
Content-Disposition: form-data; name="lastName"
Content-Type: text/plain

Ramírez Adarve
--Boundry
Content-Disposition: form-data; name="birthDate"
Content-Type: text/plain

2003-09-29
--Boundry
Content-Disposition: form-data; name="profilePicture"; filename="profile.png"
Content-Type: image/png

< ./profile.png
--Boundry--

### Completar registro de usuario sin foto de perfil
PUT {{baseUrl}}/api/users/complete-register HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  "name": "Javi",
  "lastName": "Lopez",
  "birthDate": "1922-01-29"
}

### Obtener perfil de usuario por nickname
GET {{baseUrl}}/api/users/{{nikname}} HTTP/1.1
Authorization: {{accessToken}}


### Actualizar datos del perfil
PATCH {{baseUrl}}/api/users/update-profile HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundary
Authorization: {{accessToken}}

--Boundary
Content-Disposition: form-data; name="nickname"
Content-Type: text/plain

raaul_raamirezz13
--Boundary
Content-Disposition: form-data; name="profilePicture"; filename="profile.png"
Content-Type: image/png

< ./profile.png
--Boundary--

### Solicitar restablecimiento de contraseña
POST {{baseUrl}}/api/auth/forgot-password HTTP/1.1
Content-Type: application/json

{
  "email": "adarve529@gmail.com"
}

### Restablecer la contraseña
POST {{baseUrl}}/api/auth/reset-password HTTP/1.1
Content-Type: application/json

{
  "token": "100c0785726497b98b5f3fe55ed23969f16230c876080489f0688155c714b099",
  "password": "nuevaPassword"
}

### Cambiar contraseña
PUT {{baseUrl}}/api/users/change-password HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  "currentPassword": "nuevaPassword",
  "newPassword": "nuevaPassword123"
}

### Soft Delete
DELETE {{baseUrl}}/api/users/67df10fb89829538ae8b3214?soft=true HTTP/1.1
Authorization: Bearer {{accessToken}}

### Hard Delete 
DELETE {{baseUrl}}/api/users/67e14f08c0df3a316587b0c2?soft=false HTTP/1.1
Authorization: Bearer {{accessToken}}

### Reactivar cuenta eliminada
POST {{baseUrl}}/api/users/reactivate/67df10fb89829538ae8b3214 HTTP/1.1
Authorization: Bearer {{accessToken}}

{
  "email": "rramirezsoft@gmail.com",
  "password": "nuevaPassword123"
}

### Refrescar token
POST {{baseUrl}}/api/auth/refresh HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "message": "Requesting a new access token using the refresh token"
}

### Logout 
POST {{baseUrl}}/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}
