@baseUrl = http://localhost:3000
@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ViYjk4OTE3YTMyNjdiYzQ0M2FiNDUiLCJpYXQiOjE3NDM4NTA1NTgsImV4cCI6MTc0Mzg1Nzc1OH0.CWTlPcKIbrBwfNEZos_Y_yqf9LFpMspAXYvHnvfocv0
### Registro de usuario
POST {{baseUrl}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "nickname": "tgtgt",
  "email": "yhyhy@gmail.com",
  "password": "1234567890"
}

### Validacion del email
PUT {{baseUrl}}/api/auth/validate HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  
}

### Login
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "adarve529@gmail.com",
  "password": "1234567890"
}

### Obtener perfil de usuario
GET {{baseUrl}}/api/user HTTP/1.1
Authorization: {{accessToken}}

### Subir/actualizar foto de perfil
PATCH {{baseUrl}}/api/user/profile-picture HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: {{accessToken}}

--Boundry
Content-Disposition: form-data; name="profilePicture"; filename="img.png"
Content-Type: image/png

< ./img.png
--Boundry--

### Soft Delete
DELETE {{baseUrl}}/api/user HTTP/1.1
Authorization: Bearer {{accessToken}}

### Hard Delete 
DELETE {{baseUrl}}/api/user?soft=false HTTP/1.1
Authorization: Bearer {{accessToken}}

### Registrar un lugar
POST {{baseUrl}}/api/place/find-or-create HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  "placeName": "colegio mayor aquinas"
}

### Obtener lugares
GET {{baseUrl}}/api/place
Authorization: {{accessToken}}

### Obtener un lugar por ID
GET {{baseUrl}}/api/place/67ec808ebda63b9475c082c6
Authorization: {{accessToken}}

### Crear un UserPlace
POST {{baseUrl}}/api/userPlace/create HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  "placeId": "67ec3a54609d5fface020c51",
  "status": "visited",
  "visitedAt": "2005-03-21"
}

### Actualizar UserPlace (con una fecha específica)
PATCH {{baseUrl}}/api/userPlace/update
Content-Type: application/json
Authorization: {{accessToken}}

{
  "placeId": "67ec808ebda63b9475c082c6",
  "status": "favorite"
}

### Obtener todos los UserPlaces del usuario autenticado
GET {{baseUrl}}/api/userPlace
Authorization: {{accessToken}}

### Obtener UserPlaces filtrados por categoría
GET {{baseUrl}}/api/userPlace?category=station
Authorization: {{accessToken}}

### Refrescar token
POST {{baseUrl}}/api/auth/refresh HTTP/1.1
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ViYjk4OTE3YTMyNjdiYzQ0M2FiNDUiLCJpYXQiOjE3NDM2OTQyOTAsImV4cCI6MTc0NDI5OTA5MH0.UHEcJ3REvhXcFaL0ZRGu3CzTz9LHjfjOoA3QuwX40gM

### Logout 
POST {{baseUrl}}/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}
