@baseUrl = http://localhost:3000
@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODQ3MDVmNjEzMGE1MDMzNDIzNjk3ZDAiLCJpYXQiOjE3NDk1NTEzMzYsImV4cCI6MTc0OTU1ODUzNn0.QnXlBu2BfaUx2RRYwZmwtyACDdTVLwHRjw19Rzob04s

### Completar registro de usuario
PUT {{baseUrl}}/api/user/complete-register HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  "name": "Raúl",
  "lastName": "Ramírez Adarve",
  "birthDate": "2003-09-29"
}

### Obtener perfil de usuario
GET {{baseUrl}}/api/user HTTP/1.1
Authorization: {{accessToken}}

### Subir/actualizar foto de perfil
PATCH {{baseUrl}}/api/user/profile-picture HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry
Authorization: {{accessToken}}

--Boundry
Content-Disposition: form-data; name="profilePicture"; filename="img.png"
Content-Type: image/png

< ./img.png
--Boundry--

### Actualizar datos del perfil
PATCH {{baseUrl}}/api/user/update-profile HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}
  
{
  "nickname": "adarve_529",
  "name": "Raúl",
  "lastName": "Ramírez Adarve"
}

### Cambiar contraseña
PUT {{baseUrl}}/api/user/change-password HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  "currentPassword": "1234567890",
  "newPassword": "nuevaPassword123"
}

### Soft Delete
DELETE {{baseUrl}}/api/user HTTP/1.1
Authorization: Bearer {{accessToken}}

### Hard Delete 
DELETE {{baseUrl}}/api/user?soft=false HTTP/1.1
Authorization: Bearer {{accessToken}}

### Reactivar cuenta eliminada
POST {{baseUrl}}/api/user/reactivate/67df10fb89829538ae8b3214 HTTP/1.1
Authorization: Bearer {{accessToken}}

{
  "email": "rramirezsoft@gmail.com",
  "password": "nuevaPassword123"
}