@baseUrl = http://localhost:3000
@accessToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODQ1Yjg2ZWU3NjA0YjY3ZDg1ZGU3NGIiLCJpYXQiOjE3NDkzOTk2NjIsImV4cCI6MTc0OTQwNjg2Mn0.ifauB6Qqg0REwBZ7SV3HdewZCObZ3EhMZgL5ONviZaY

### Registro de usuario con rol de user
POST {{baseUrl}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "nickname": "rulass",
  "email": "rramirezsoft@gmail.com",
  "password": "1234567890"
}

### Registro de usuario con rol de admin
POST {{baseUrl}}/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "nickname": "admin123",
  "email": "admin@gmail.com",
  "password": "adminPassword",
  "role": "admin"
}

### Validacion del email
PUT {{baseUrl}}/api/auth/validate HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}

{
  "verificationCode": "944231"
}

### Reenviar código de verificación
POST {{baseUrl}}/api/auth/resend-code HTTP/1.1
Authorization: {{accessToken}}

### Login
POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "adarve529@gmail.com",
  "password": "1234567890"
}

### Login / Registro con Google
GET {{baseUrl}}/api/auth/google HTTP/1.1
Accept: application/json

### Solicitar restablecimiento de contraseña
POST {{baseUrl}}/api/auth/forgot-password HTTP/1.1
Content-Type: application/json

{
  "email": "adarve529@gmail.com"
}

### Restablecer la contraseña
POST {{baseUrl}}/api/auth/reset-password HTTP/1.1
Content-Type: application/json

{
  "token": "100c0785726497b98b5f3fe55ed23969f16230c876080489f0688155c714b099",
  "password": "nuevaPassword"
}

### Refrescar token
POST {{baseUrl}}/api/auth/refresh HTTP/1.1
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2ViYjk4OTE3YTMyNjdiYzQ0M2FiNDUiLCJpYXQiOjE3NDM2NzEzNDgsImV4cCI6MTc0NDI3NjE0OH0.Ebn_H3dbQtItWIkQFdMluj3f4sTnTMTSn9j7glgocl0

### Logout 
POST {{baseUrl}}/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: {{accessToken}}